services:
  - type: web
    name: bache-rag-api
    env: python
    buildCommand: |
      # 1️⃣ Ensure all dependencies are installed
      pip install -r requirements.txt

      # 2️⃣ Initialize or update the chris-bache-archive submodule
      git submodule update --init --recursive --remote

    startCommand: |
      # 3️⃣ Always fetch the latest verified vector bundle on container start
      #    (this guarantees the FAISS + Parquet files exist even on a fresh instance)
      bash -lc "./scripts/fetch_vectors.sh && uvicorn app:app --host 0.0.0.0 --port $PORT"
